### ISSUE TITLE
Change Open Source & Decentralized

### ISSUE THREAD

**Issue by seniorm0ment** [bookwyrm-social/join-bookwyrm#3]
Consider changing the template from "open source" to "libre" or "libre and open source".
Also having Libre as an icon (alongside "decentralized, friendly, anti-corporate) might be nice.

Could it maybe also make more sense to change "decentralized" to say "federated"?

**Comment by mouse-reeve** [comment]
I've changed the wording around "open source" elsewhere - can you point out specifically where it's used? I'm not finding it at a cursory grep.

**Comment by seniorm0ment** [comment]
https://bookwyrm.social/
front page

**Comment by mouse-reeve** [comment]
Thanks and fixed! It isn't in the source code, which is why I missed it.

The reason I'm using decentralized here is that I think it's a more widely understood term than federated. While I understand the technical distinction between a federated protocol like ActivityPub and a protocol like IPFS or torrents, it's my understanding that "decentralized" is commonly used, even in technical contexts, as an umbrella term that includes federated systems. In the [official AP documentation](https://www.w3.org/TR/activitypub/), for example. 

I hope to make the information about bookwyrm accessible to an audience that isn't already familiar with Mastodon and other AP services (and really, to an audience which doesn't care about the technical aspects at all), which is why I went with that wording.

**Comment by seniorm0ment** [comment]
that is understandable, maybe it could be worth adding a small font note directly under the decentralized icon on that page that says something like "federated over activitypub" or something along those lines?

I agree with making it easy to understand for less technical users, however I believe it still should be accurate and not misleading especially for nore technical users so they get the proper impression. Federation is technically decentralized to an extent I guess, but I think making it clear it's federated would be nice.

It could also be beneficial to hyperlink some of the text described on the page to allow new users to explore the "fediverse" easier" Maybe hyperlink "mastodon", "activitypub", "federated", etc to their respectful pages"

**Comment by seniorm0ment** [comment]
also I see the page updated, did you change the word open source to something along the lines of libre? or just remove that? because it looks like you just removed it?

**Comment by mouse-reeve** [comment]
I just removed it, it didn't seem pertinent to that copy when there's info about the source in the footer.

It sounds like you value precise language, which is great. But I disagree that using decentralized is incorrect or misleading - I see it used even in very technical contexts to describe ActivityPub. I hope that in the documentation it's clear that bookwyrm uses activitypub, and I certainly don't want to obfuscate that fact, I just don't think that the word "decentralized" is at odds with that goal. 

Just to be super clear since a few different things are at play, the text on bookwyrm.social's logged out landing page next to the logo, which came up earlier in this conversation, is the instance description - it's determined by the instance admin (in this case me), and it's meant to give prospective users a very brief introduction to that particular instance. 

When you suggest adding links, my interpretation is that you mean on the joinbookwyrm.com page, which is meant to provide a general introduction to bookwyrm as a service. I agree! I think that's a helpful addition.
